### PR TITLE
Convert checker.py to Python 3

### PR DESCRIPTION
**Pull request by vinhtq115**
I converted `checker.py` to Python 3 and tested it with my PS3 firmware files (1 dumped on OFW, 1 dumped on REBUG 4.84.2 D-REX). It behaved exactly like Python 2 version.

Output examples:
```
(ps3) C:\Users\vinhtq115\PyPS3tools\PyPS3checker>python checker.py R:\hacked.hex



  ____        ____  ____ _____      _               _
 |  _ \ _   _|  _ \/ ___|___ /  ___| |__   ___  ___| | _____ _ __
 | |_) | | | | |_) \___ \ |_ \ / __| '_ \ / _ \/ __| |/ / _ \ '__|
 |  __/| |_| |  __/ ___) |__) | (__| | | |  __/ (__|   <  __/ |
 |_|    \__, |_|   |____/____/ \___|_| |_|\___|\___|_|\_\___|_|
        |___/                                               v0.11.x

 Python checker script for PS3 flash memory dump files
 Copyright (C) 2015 littlebalup@gmail.com


Loading file "R:\hacked.hex" to memory...
 Done


******* Getting flash type *******
  Flash type : NAND (partial dump, 239MB)


******* Getting SKU identification datas *******
  idps = 0x01
  metldr0 = 0xEDA0
  metldr1 = 0x0ED6

  Matching SKU : OK
   CECHAxx (COK-001)
   Minimum version 1.00


******* Getting SDK versions *******
  ROS0 : 484.000
  ROS1 : 484.000


******* Checking Header_Magic *******
002.01   Header Magic 0x00 Filled Area 0 : OK
002.02   Header Magic : OK
002.03   Header Magic 0x00 Filled Area 1 : OK


******* Checking flash_region_table *******
003.01   Flash Region Table Header : OK
003.02   asecure_loader Offset - Length : OK
003.03   asecure_loader Name : OK
003.04   eEID Offset - Length : OK
003.05   eEID Name : OK
003.06   cISD Offset - Length : OK
003.07   cISD Name : OK
003.08   cCSD Offset - Length : OK
003.09   cCSD Name : OK
003.10   trvk_prg Offset - Length : OK
003.11   trvk_prg Name : OK
003.12   trvk_pkg Offset - Length : OK
003.13   trvk_pkg Name : OK
003.14   creserved_0 Offset - Length : OK
003.15   creserved_0 Name : OK
003.16   ros Offset - Length : OK
003.17   ros Name : OK
003.18   cvtrm Offset - Length : OK
003.19   cvtrm Name : OK
003.20   Flash Region Table 0x00 Filled Area : OK


******* Checking asure_loader_region *******
004.01   asecure_loader Header : OK
004.02   metldr Offset : OK
004.03   metldr Length : OK
004.04   metldr Name : OK
004.05   metldr RevKey : OK
004.06   metldr Binary Size : OK
004.07   metldr Statistics : OK
004.08   asecure_loader 0x00 Filled Area : OK


******* Checking eEID_region *******
005.01   eEID Header : OK
005.02   EID0 Offset - Length : OK
005.03   EID1 Offset - Length : OK
005.04   EID2 Offset - Length : OK
005.05   EID3 Offset - Length : OK
005.06   EID4 Offset - Length : OK
005.07   EID5 Offset - Length : OK
005.08   EID0 IDPS0 : OK
005.09   EID0 IDPS1 : OK
005.10   EID0 Static : OK
005.11   EID2 BlockSize/Padding : OK
005.12   EID3 Static0 : OK
005.13   EID3 Static1 : OK
005.14   EID3 Static2 : OK
005.15   EID5 IDPS0 : OK
005.16   EID5 IDPS1 : OK
005.17   EID5 Static : OK
005.18   eEID Region 0xFF Filled Area : OK
005.19   eEID Statistics0 : OK
005.20   eEID Statistics1 : OK


******* Checking cISD_region *******
006.01   cISD Header : OK
006.02   cISD0 Offset - Length : OK
006.03   cISD1 Offset - Length : OK
006.04   cISD2 Offset - Length : OK
006.05   cISD0 0xFF Filled Area : OK
006.06   cISD1 IDLog Header : OK
006.07   cISD1 Semistatic 1 : OK
006.08   cISD1 Semistatic 2 : OK
006.09   cISD1 0xFF Filled Area 0 : OK
006.10   cISD1 Static : OK
006.11   cISD1 Semistatic 3 : OK
006.12   cISD1 0xFF Filled Area 1 : OK
006.13   cISD1 Statistics : OK
006.14   cISD2 : OK
006.15   cISD 0xFF Filled Area : OK


******* Checking cCSD_region *******
007.01   cCSD Header : OK
007.02   cCSD Entry Table : OK
007.03   cCSD 0xFF Filled Area : OK


******* Checking Revokation_region *******
008.00   trvk_prg Region Header : OK
008.01   trvk_prg0 SCE : OK
008.02   trvk_prg0 Hash : OK
  Size = 0x2C0
  MD5 = 9C3A02E2A8067B0B4200B0F195236F74
  Version = 2.80 (from PUP)

008.03   trvk_prg1 SCE : OK
008.04   trvk_prg1 Hash : OK
  Size = 0x2E0
  MD5 = 78629D24BD721488F3A1E846938F87DF
  Version = 3.55 (from PUP)

008.00   trvk_pkg Region Header : OK
008.05   trvk_pkg0 SCE : OK
008.07   trvk_pkg1 SCE : OK


******* Checking Unreferenced_Area *******
008.08   unreferenced area 0xFF filled : OK


******* Checking CoreOS_region *******
009.00   ROS Header : OK
009.01   ROS0 Header : OK
009.02   ROS0 Hash : OK
  Size = 0x6FFFE0
  MD5 = 7972C66E5CD5FD26772E53BA8638EA89
  Version = 4.84.2 REBUG D-REX

009.03   ROS1 Header : OK
009.04   ROS1 Hash : WARNING!
  Size = 0x6FFFE0
  MD5 = C1C16CD98FADE08353BD8E31DB33AD17
  Version = (unknown)



******* Checking cvtrm_region *******
010.01   cvtrm Header : OK
010.02   cvtrm Header Static 1 : OK
010.03   vtrm Magic 1 : OK
010.05   vtrm Magic 2 : OK
010.07   cvtrm 0x00 Filled Area : OK


******* Checking cell_ext_os_area *******
011.01   cell_ext_os_area Header : OK
011.02   cell_ext_os_area 0xFF Filled Area 0 : OK
011.03   cell_ext_os_area Break Section : OK
011.04   cell_ext_os_area 0xFF Filled Area 1 : OK


******* Checking datamatches *******
per console nonce : OK
metldr size : OK
vtrm header datas : OK
vtrm : OK


******* Checking repetitions *******
Header Magic Repetition : OK
asecure_loader Repetition : OK
eEID Repetition : OK
cISD Repetition : OK
cCSD Repetition : OK
trvk_prg Repetition : OK
trvk_pkg Repetition : OK
ros Repetition : OK
cvtrm Repetition : OK


******* Additional information *******
MAC address : <redacted>
CID : <redacted>
eCID : <redacted>
board_id (part of console S/N) : <redacted>
kiban_id (board barcode) : <redacted>



******* Checks completed *******

Total number of checks = 113
Number of dangers = 0
Number of warnings = 1

Following check(s) returned a
WARNING!
  009.04   ROS1 Hash

All checks done in 1.34 seconds.

(ps3) C:\Users\vinhtq115\PyPS3tools\PyPS3checker>python checker.py R:\original.hex



  ____        ____  ____ _____      _               _
 |  _ \ _   _|  _ \/ ___|___ /  ___| |__   ___  ___| | _____ _ __
 | |_) | | | | |_) \___ \ |_ \ / __| '_ \ / _ \/ __| |/ / _ \ '__|
 |  __/| |_| |  __/ ___) |__) | (__| | | |  __/ (__|   <  __/ |
 |_|    \__, |_|   |____/____/ \___|_| |_|\___|\___|_|\_\___|_|
        |___/                                               v0.11.x

 Python checker script for PS3 flash memory dump files
 Copyright (C) 2015 littlebalup@gmail.com


Loading file "R:\original.hex" to memory...
 Done


******* Getting flash type *******
  Flash type : NAND (partial dump, 239MB)


******* Getting SKU identification datas *******
  idps = 0x01
  metldr0 = 0xEDA0
  metldr1 = 0x0ED6

  Matching SKU : OK
   CECHAxx (COK-001)
   Minimum version 1.00


******* Getting SDK versions *******
  ROS0 : 488.000
  ROS1 : 488.000


******* Checking Header_Magic *******
002.01   Header Magic 0x00 Filled Area 0 : OK
002.02   Header Magic : OK
002.03   Header Magic 0x00 Filled Area 1 : OK


******* Checking flash_region_table *******
003.01   Flash Region Table Header : OK
003.02   asecure_loader Offset - Length : OK
003.03   asecure_loader Name : OK
003.04   eEID Offset - Length : OK
003.05   eEID Name : OK
003.06   cISD Offset - Length : OK
003.07   cISD Name : OK
003.08   cCSD Offset - Length : OK
003.09   cCSD Name : OK
003.10   trvk_prg Offset - Length : OK
003.11   trvk_prg Name : OK
003.12   trvk_pkg Offset - Length : OK
003.13   trvk_pkg Name : OK
003.14   creserved_0 Offset - Length : OK
003.15   creserved_0 Name : OK
003.16   ros Offset - Length : OK
003.17   ros Name : OK
003.18   cvtrm Offset - Length : OK
003.19   cvtrm Name : OK
003.20   Flash Region Table 0x00 Filled Area : OK


******* Checking asure_loader_region *******
004.01   asecure_loader Header : OK
004.02   metldr Offset : OK
004.03   metldr Length : OK
004.04   metldr Name : OK
004.05   metldr RevKey : OK
004.06   metldr Binary Size : OK
004.07   metldr Statistics : OK
004.08   asecure_loader 0x00 Filled Area : OK


******* Checking eEID_region *******
005.01   eEID Header : OK
005.02   EID0 Offset - Length : OK
005.03   EID1 Offset - Length : OK
005.04   EID2 Offset - Length : OK
005.05   EID3 Offset - Length : OK
005.06   EID4 Offset - Length : OK
005.07   EID5 Offset - Length : OK
005.08   EID0 IDPS0 : OK
005.09   EID0 IDPS1 : OK
005.10   EID0 Static : OK
005.11   EID2 BlockSize/Padding : OK
005.12   EID3 Static0 : OK
005.13   EID3 Static1 : OK
005.14   EID3 Static2 : OK
005.15   EID5 IDPS0 : OK
005.16   EID5 IDPS1 : OK
005.17   EID5 Static : OK
005.18   eEID Region 0xFF Filled Area : OK
005.19   eEID Statistics0 : OK
005.20   eEID Statistics1 : OK


******* Checking cISD_region *******
006.01   cISD Header : OK
006.02   cISD0 Offset - Length : OK
006.03   cISD1 Offset - Length : OK
006.04   cISD2 Offset - Length : OK
006.05   cISD0 0xFF Filled Area : OK
006.06   cISD1 IDLog Header : OK
006.07   cISD1 Semistatic 1 : OK
006.08   cISD1 Semistatic 2 : OK
006.09   cISD1 0xFF Filled Area 0 : OK
006.10   cISD1 Static : OK
006.11   cISD1 Semistatic 3 : OK
006.12   cISD1 0xFF Filled Area 1 : OK
006.13   cISD1 Statistics : OK
006.14   cISD2 : OK
006.15   cISD 0xFF Filled Area : OK


******* Checking cCSD_region *******
007.01   cCSD Header : OK
007.02   cCSD Entry Table : OK
007.03   cCSD 0xFF Filled Area : OK


******* Checking Revokation_region *******
008.00   trvk_prg Region Header : OK
008.01   trvk_prg0 SCE : OK
008.02   trvk_prg0 Hash : OK
  Size = 0x2E0
  MD5 = 811733A6FF2D307FBB3C234A5EC9EE2A
  Version = 3.40 (from PUP)

008.03   trvk_prg1 SCE : OK
008.04   trvk_prg1 Hash : OK
  Size = 0x2E0
  MD5 = 16CB4E101F0D6D24525B0E6F1A6681AD
  Version = 3.30 (from PUP)

008.00   trvk_pkg Region Header : OK
008.05   trvk_pkg0 SCE : OK
008.07   trvk_pkg1 SCE : OK


******* Checking Unreferenced_Area *******
008.08   unreferenced area 0xFF filled : OK


******* Checking CoreOS_region *******
009.00   ROS Header : OK
009.01   ROS0 Header : OK
009.02   ROS0 Hash : OK
  Size = 0x6FFFE0
  MD5 = 0D96DA1FA66F61FBA9CD1615D9AD20AB
  Version = 4.88 Evilnat Cobra

009.03   ROS1 Header : OK
009.04   ROS1 Hash : OK
  Size = 0x6FFFE0
  MD5 = 36A0D80FB18E9D6FD7635217D59FA726
  Version = 4.88 CEX/SEX OFW/HFW



******* Checking cvtrm_region *******
010.01   cvtrm Header : OK
010.02   cvtrm Header Static 1 : OK
010.03   vtrm Magic 1 : OK
010.05   vtrm Magic 2 : OK
010.07   cvtrm 0x00 Filled Area : OK


******* Checking cell_ext_os_area *******
011.01   cell_ext_os_area Header : OK
011.02   cell_ext_os_area 0xFF Filled Area 0 : OK
011.03   cell_ext_os_area Break Section : OK
011.04   cell_ext_os_area 0xFF Filled Area 1 : OK


******* Checking datamatches *******
per console nonce : OK
metldr size : OK
vtrm header datas : OK
vtrm : OK


******* Checking repetitions *******
Header Magic Repetition : OK
asecure_loader Repetition : OK
eEID Repetition : OK
cISD Repetition : OK
cCSD Repetition : OK
trvk_prg Repetition : OK
trvk_pkg Repetition : OK
ros Repetition : OK
cvtrm Repetition : OK


******* Additional information *******
MAC address : <redacted>
CID : <redacted>
eCID : <redacted>
board_id (part of console S/N) : <redacted>
kiban_id (board barcode) : <redacted>



******* Checks completed *******

Total number of checks = 113
Number of dangers = 0
Number of warnings = 0

All checks done in 1.37 seconds.
```

### CODE REVIEW

**Comment by littlebalup** [comment]
Thank you for your effort. Good work. Really appreciated.

The way those tools as been done is to be compatible with the suite of dumping tools from judges : https://github.com/hjudges/NORway
That's why it has been coded with Python 2. So I'd like to keep python 2 anyway. But I'm not against to add a Python 3 alternative by renaming the script like "checker_py3.py" or similar (and the .bat). The .xml files must be unique and shared for both.

Not mandatory but you can go even deeper with python 3 regarding the way it handle binary data. Cleaning a lot of stuff. But it's a huge work.

note : colorama is fully optionnal.

I tested really quicly your changes with Python 3.8 and 3.10. Both with this error:
`Traceback (most recent call last):
  File "checker.py", line 486, in <module>
    tag = string2hex(k).upper()
  File "checker.py", line 91, in string2hex
    return "".join("{:02x}".format(ord(chr(c))) for c in data)
TypeError: 'int' object is not iterable`

**Comment by vinhtq115** [comment]
> Thank you for your effort. Good work. Really appreciated.
> 
> The way those tools have been done is to be compatible with the suite of dumping tools from judges : https://github.com/hjudges/NORway That's why it has been coded with Python 2. So I'd like to keep python 2 anyway. But I'm not against to add a Python 3 alternative by renaming the script like "checker_py3.py" or similar (and the .bat). The .xml files must be unique and shared for both.

I have restored original files and renamed the new ones. 

Regarding the XML files, the original files contain Byte Order Mark (UTF-8 with BOM) and Python 3 couldn't parse it so I just removed them (it became UTF-8 without BOM). New files work fine with both Python 2 and 3.

> Not mandatory but you can go even deeper with python 3 regarding the way it handle binary data. Cleaning a lot of stuff. But it's a huge work.
> 
> note : colorama is fully optionnal.

`colorama` is still optional. The behavior is the same as the Python 2 script.

> I tested really quicly your changes with Python 3.8 and 3.10. Both with this error: `Traceback (most recent call last): File "checker.py", line 486, in <module> tag = string2hex(k).upper() File "checker.py", line 91, in string2hex return "".join("{:02x}".format(ord(chr(c))) for c in data) TypeError: 'int' object is not iterable`

Could you check the new script? The fix was the same as line 412.

**Comment by littlebalup** [comment]
image

The reverse function is broken too
image

You should test with all types of dumps, good and bad.

**Comment by vinhtq115** [comment]
> You should test with all types of dumps, good and bad.

Is there anyway to generate a bad dump to test? I only have 2 dumps from my NAND PS3 and none of them has this error.

**Comment by littlebalup** [comment]
You will have to generate errors by hex editing your the dumps. For any type of checking. This is the hardest thing for debugging. You can find some dumps [[here](https://www.dropbox.com/sh/m419t89t4flw1xo/AAAL_VcOkw5V3roB5otMOYbHa?dl=0)] (url) but it is not exhaustive.

**Comment by littlebalup** [comment]
Nice! Sounds good.

As colorama is optional I think you can remove the requirements.txt.

The readme should be changed like this:
`System requirements:
-------------------
Using checker.py:
 - Any system able to run Python 2.7.x (Windows, Linux, MAC... )
 - Python 2.7.2 or any upper Python 2 version : https://www.python.org
 - (optional to display colored text) Colorama python module`
Using checker_py3.py:
 - Any system able to run Python 3.x (Windows, Linux, MAC... )
 - Python 3.5 or any upper Python 3 version : https://www.python.org
 - (optional to display colored text) Colorama python module`

**Comment by vinhtq115** [comment]
> Nice! Sounds good.
> 
> As colorama is optional I think you can remove the requirements.txt.
> 
> The readme should be changed like this:
> 
> ```
> System requirements:
> -------------------
> Using checker.py:
>  - Any system able to run Python 2.7.x (Windows, Linux, MAC... )
>  - Python 2.7.2 or any upper Python 2 version : https://www.python.org
>  - (optional to display colored text) Colorama python module`
> Using checker_py3.py:
>  - Any system able to run Python 3.x (Windows, Linux, MAC... )
>  - Python 3.5 or any upper Python 3 version : https://www.python.org
>  - (optional to display colored text) Colorama python module
> ```

Done

**Pull request merged**
